# Generated by Django 4.2.7 on 2023-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gendre',
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
