# Generated by Django 4.2.7 on 2023-12-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_patient_gendre_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
